
# This is a sample request that TH Backend will send us
POST http://localhost:8000/message
Content-Type: application/json

{
    "type": "audio",
    "data": "base64data",
    "user_id": "from TH Backend",
    "user_name": "from TH Backend",
    "token": "from TH Backend"
}
